location = /sw.js {
    include include.d/nocache.conf;
    add_header Service-Worker-Allowed "/" always;
}

location = /manifest.webmanifest {
    include include.d/nocache.conf;
}

location / {
    try_files $uri $uri/ /index.html;
    include include.d/nocache.conf;
    {{if .Env.BACKEND_FRAME_ORIGIN}}
    add_header Content-Security-Policy "frame-ancestors 'self' {{ .Env.BACKEND_FRAME_ORIGIN }}" always;
    {{else}}
    add_header X-Frame-Options SAMEORIGIN always;
    {{end}}
}

location /assets {
   alias /var/www/public/assets/;
   include include.d/allcache.conf;
}

include "include.d/spa.conf";
