location = /sw.js {
    include include.d/nocache.conf;
}

location = /manifest.webmanifest {
    include include.d/nocache.conf;
}

location / {
    try_files $uri $uri/ /index.html;
    include include.d/nocache.conf;
}

location /assets {
   alias /var/www/public/assets/;
   include include.d/allcache.conf;
}

include "include.d/spa.conf";
